repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.52.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tfsec
      - id: checkov
        args: ["-d", "."]
