name: CI
on: [push, pull_request]

runs-on

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform init
        name: Terraform init
      - uses: pre-commit/action@v2.0.0
        name: Run pre-commit
      - run: terraform validate
        name: Run terraform validate

  Compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install checkov
        name: Install dependencies
      - run: checkov -d .
        name: Run checkov

